#!/usr/bin/env python3
"""Derive HEIC and PDF fixtures from the sample photos in Documents/.

The brief's Milestone 1 must prove the HEIC and PDF input paths; the sample
set only has JPEGs, so this script builds:

  fixtures/derived/page_06.heic   the upright page re-encoded as HEIC
  fixtures/derived/pages.pdf      2 pages: the same photo embedded as an
                                  image page, then a born-digital text page
                                  (rendered by PyMuPDF at 200 dpi → OCR)
  fixtures/derived/page_07_exif.jpg  page 7 stored rotated 90° CW with EXIF
                                  Orientation=8, to prove exif_transpose is honoured
  fixtures/derived/page_07_upside_down.jpg  page 7 stored rotated 180° with
                                  no EXIF, to exercise the upside-down check

Run:  python tools/make_fixtures.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pymupdf
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from usefultext.preprocess import load_image, register_heif  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "Documents"
OUT = ROOT / "fixtures" / "derived"


def main() -> int:
    if not register_heif():
        print("pillow-heif is required to write HEIC fixtures", file=sys.stderr)
        return 1
    OUT.mkdir(parents=True, exist_ok=True)
    upright = next(SRC.glob("a1835f29*"), None)
    other = next(SRC.glob("cc36b71b*"), None)
    if not upright or not other:
        print("expected the sample photos in Documents/", file=sys.stderr)
        return 1

    img = load_image(upright)
    img.save(OUT / "page_06.heic", quality=85)

    # A JPEG stored rotated 90° CW; EXIF Orientation=8 tells viewers to
    # rotate it 90° CCW (camera-style). exif_transpose must undo it.
    src = load_image(other)
    rotated = src.transpose(Image.Transpose.ROTATE_270)
    exif = Image.Exif()
    exif[274] = 8
    rotated.save(OUT / "page_07_exif.jpg", quality=85, exif=exif.tobytes())
    # Upside-down pixels, no EXIF at all.
    src.transpose(Image.Transpose.ROTATE_180).save(OUT / "page_07_upside_down.jpg", quality=85)

    pdf = pymupdf.open()
    page = pdf.new_page(width=img.width * 72 / 200, height=img.height * 72 / 200)
    page.insert_image(page.rect, filename=str(upright))
    text_page = pdf.new_page(width=595, height=842)  # A4, born-digital text
    body = (
        "Chapter Two\n\n"
        "This page was generated by PyMuPDF rather than photographed, so it "
        "exercises the PDF render path at 200 dpi.\n\n"
        "Fred looked out at the sea. The iceberg had been there for many, many "
        "years, and everyone assumed it always would be.\n\n"
        "Page numbers such as page_10 must sort after page_9."
    )
    text_page.insert_textbox(pymupdf.Rect(72, 72, 523, 770), body, fontsize=13, fontname="helv")
    pdf.save(OUT / "pages.pdf")
    pdf.close()
    print("wrote", *[p.name for p in sorted(OUT.iterdir())], "→", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
